name: "Test android-emulator-runner"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: macOS-latest
    strategy:
      matrix:
        api-level: [28, 29]
        target: [default, google_apis]
        abi: [x86, x86_64]
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: build and test
      run: |
        npm install
        npm run build
        npm test

    - name: run action
      uses: ./
      with: 
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        abi: ${{ matrix.abi }}
        headless: true
